### ISSUE TITLE
OglModel causes GUIManager.createGUI to fail

### ISSUE THREAD

**Issue by psomers3** [sofa-framework/SofaPython3#60]
I hate to be the one to bring another issue to the table, but when I run the following code in runSofa, it works fine, but when I run it directly in python, it crashes with the error below. When I comment out the `visual = ...` line it does not crash. Any thoughts? Am I using the GUIManager correctly? I am running on a latest masterbranch compilation of sofa with Ubuntu 18.4 (on Windows wsl).

```python
from SofaRuntime import PluginRepository
import Sofa
import Sofa.Gui
import sys, os


def createScene(root):
    root.addObject("RequiredPlugin", name="SofaOpenglVisual")
    obj = root.addChild("obj")
    meshLoader = obj.addObject('MeshObjLoader', name="loader", filename="mesh/Armadillo_simplified.obj", scale=10)
    visual = obj.addObject('OglModel', name="visual", src="@loader")
    return root


if __name__ == '__main__':
    print("Supported GUIs are " + Sofa.Gui.GUIManager.ListSupportedGUI(","))
    PluginRepository.addFirstPath(os.path.split(os.path.split(sys.executable)[0])[0] + "/plugins")

    root = Sofa.Core.Node("root")
    createScene(root)

    # Initialize all components found in the scene
    Sofa.Simulation.init(root)

    # Launch the GUI
    Sofa.Gui.GUIManager.Init("qt")
    Sofa.Gui.GUIManager.createGUI(root)
    Sofa.Gui.GUIManager.MainLoop()
    Sofa.Gui.GUIManager.closeGUI()

 ```

Error:
```terminal
[ERROR]   [SofaRuntime] RuntimeError: basic_string::_M_construct null not valid
Traceback (most recent call last):
  File "/usr/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/psomers/pycharm-community-2020.2.1/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/psomers/pycharm-community-2020.2.1/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/psomers/git/moveable_view/ROI_extraction.py", line 28, in <module>
    Sofa.Gui.GUIManager.createGUI(root)
```

**Comment by jnbrunet** [comment]
Hey @psomers3 

Sorry for the late answer.

Could you try adding `Sofa.Simulation.initVisual(root)` just after `Sofa.Simulation.init(root)`? I think the OglModel needs this visual initialization.

**Comment by psomers3** [comment]
So I just copied the excerpt from my issue above before trying your suggestion... And now it works fine with just passing root to MainLoop(). So I don't know what changed because I don't recall recompiling anything. Weird.
Thank you for the response, even though the problem apparently fixed itself.
